### ISSUE TITLE
PIN orders still have a phone number in the query if a number was typed before

### ISSUE THREAD

**Issue by Furzel** [bitrefill/airfill-widget#109]
To reproduce : 

go on the widget -> input whatever number -> pick USA -> pick Itunes -> create an order 

the number gets sent but the backend expects a blank number since it's PIN and it messes up with some of our providers hack. 

exemple order from one of our customers : https://bitrefill-support.herokuapp.com/order/5b4385b18c4b0400041189e6
and from me : https://bitrefill-support.herokuapp.com/order/5b4393008c4b040004118a8b

**Comment by Maximization** [comment]
FYI @bitrefill/frontend-team there's also an issue in the backend to fix this on that end. This is in addition to that
