### ISSUE TITLE
Replace d_operator.png default image

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#110]
Low priority enhancement:

![image](https://user-images.githubusercontent.com/92292/42504923-81c17492-843d-11e8-9906-21ac862419f3.png)

This icon has been there since I put it there week 1. It's not great and was never meant to last this long. I propose we make something based on the voucher card card idea, just fill one with grey background? People will get the idea.
Then I can upload it as operator.png

**Comment by wille** [comment]
![image](https://user-images.githubusercontent.com/18327818/42513344-fb072cb6-8456-11e8-9471-9cee423a7d12.png)

something like this?

**Comment by ziggamon** [comment]
Yep. Maybe one that keeps the shape of the symbol? height wise I mean.

**Comment by wille** [comment]
don't want to spend more time in gimp now since I suck at it so I'll ask Anna to fix something great for us

**Comment by ziggamon** [comment]
Good idea :)

**Comment by wille** [comment]
![image](https://user-images.githubusercontent.com/18327818/42822709-0401e86c-89dc-11e8-808c-e357a30ed825.png)

<img width="228" alt="exclude 2x" src="https://user-images.githubusercontent.com/18327818/42822727-0a610210-89dc-11e8-82ec-ba8ce300155a.png">

**Comment by wille** [comment]
@ziggamon

**Comment by ziggamon** [comment]
Looks good, I'll update it!
