### ISSUE TITLE
"Ethereum mode" should go into the widget

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#112]
Right now adding /ethereum changes copy, but would be good if it went all the way to the widget to set default payment method to ethereum as well. 

Less important and bigger feature is displaying pricing in ETH as well in the "Select Amount" step. Maybe a temporary workaround can be that if $currency != "btc" then don't display any pricing in that step. Later we can make it work properly with Ethereum as well.

**Comment by wille** [comment]
Going to /refill/coin will put that coin in the top in the payment menu, and will preselect it.
All `bitcoin` strings are replaced accordingly as well.
Whats left is coin prices in the package step.
