### ISSUE TITLE
"No it's not correct" button doesn't let the user change operator.

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#119]
https://cl.ly/3M0A0z123A0Y

Correct behavior: Scroll down to the page with all other mobile operators. 

Bonus point based on the screenshot: Group results by type. Will file backend ticket to make sure good stuff is returned there.

**Comment by wille** [comment]
Bonus points fixed in https://github.com/bitrefill/bitrefill-dashboard/issues/330.

This is the current behaviour of the "no it's not correct" button. Whats missing?

![peek 2018-08-02 14-29](https://user-images.githubusercontent.com/18327818/43583691-96758ec0-9660-11e8-8e5c-61412e09074f.gif)

**Comment by ziggamon** [comment]
Looks great! Closing this one!
