### ISSUE TITLE
iOS: Keyboard doesn't close after copy

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#124]
On the iOS app, after copying the amount the keyboard is having a hard time closing. Can get it to close by clicking "Change" button but it's a little clunky. It would be good if we can find a way to get it to close when clicking elsewhere on the page, and at the same time not have that interfere with the selection of the text and manual copying.

**Comment by wille** [comment]
Keyboard hidden. This was the cause.

8780348604308287ea6d2b79ed30eefa0baa6f56

Migrating to TypeScript will prevent stuff like this :P
