### ISSUE TITLE
"Refill sent" text

### ISSUE THREAD

**Issue by wille** [bitrefill/airfill-widget#136]
So I recently did a LN purchase and it was amazing and smooth, but want to improve "refill sent" label to something more related to vouchers etc

![untitled](https://user-images.githubusercontent.com/18327818/44262004-b89d5180-a219-11e8-88d8-c1d9150031aa.png)

**Comment by ziggamon** [comment]
Suggestion:

"Delivery in progress" ?

Byline:
"Your payment has been accepted, and we're now working on sending through the product you purchased".

**Comment by wille** [comment]
Added this change to backend for us to easily get operator type from order object only.
https://github.com/bitrefill/bitrefill-backend/commit/b65a68d56609fc8e2f2a7c8190cd4c2d93aebb91
When it's live I'll continue with this

**Comment by Furzel** [comment]
Want me to push it live ?

**Comment by wille** [comment]
@Furzel  no hurries but lmk when it's up :dancer:

**Comment by wille** [comment]
also here 
![image](https://user-images.githubusercontent.com/18327818/44737907-892cf580-aaf3-11e8-93dc-4241d85ee089.png)

**Comment by wille** [comment]
Issue moved to [bitrefill/bitrefill-dashboard #421](https://github.com/bitrefill/bitrefill-dashboard/issues/421) via [**ZenHub**](https://www.zenhub.com/)
