### ISSUE TITLE
Show Account input instead of phone for non-refills

### ISSUE THREAD

**Issue by juscamarena** [bitrefill/airfill-widget#139]
https://www.bitrefill.com/refill/dth-reliance-big-tv-india/
https://old.bitrefill.com/dth-reliance-big-tv-india/

In the old bitrefill-web we correctly had the input named as 'Enter account number to get started:'

Confusingly recipientType isn't set to 'account' and  us set only when recipientType is not 'none', 'email' and then only shows up when operator.type is not equal to 'refill' || 'data' || 'voip' in bitrefill-web in operator.hbs

```
			{{#ifeq operator.recipientType 'none'}}
            {{else ifeq operator.recipientType 'username'}}
                <h3>Enter username or post/comment url to get started:</h3>
            {{else ifeq operator.recipientType 'email'}}
                <h3>Enter account email to get started:</h3>
            {{else}}
                <h3>{{ifOperatorIsMobile operator 'Enter phone number to get started:' 'Enter account number to get started:'}}</h3>
			{{/ifeq}}
```

We should probably have a new recipientType set to 'account' and set the DTH and other relevant products to it and not to "recipientType": "phone_number" unless it actually needs a phone number. 

Thoughts?

**Comment by Maximization** [comment]
Yeah makes sense to change `recipientType: "phone_number"` from dth operators to `account`, or more specific `dth_account` @Furzel

**Comment by Furzel** [comment]
Yes and probably remove any validation for it because we usually don't know what the input is supposed to look like.

**Comment by wille** [comment]
@Maximization @Furzel let me know if any recipientType changes etc

**Comment by juscamarena** [comment]
@Maximization well depends, it's not only DTH that need account input stuff. https://www.bitrefill.com/refill/tuc-nicaragua/ needs it as well (we can't validate there either) and probably others as I didn't really dig deep. Unless we want to be super specific I think a new recipientType 'account' is fine?

**Comment by Maximization** [comment]
Issue moved to [bitrefill/bitrefill-backend #578](https://github.com/bitrefill/bitrefill-backend/issues/578) via [**ZenHub**](https://www.zenhub.com/)
