### ISSUE TITLE
PIN refills and such should not require a phone number

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#19]
Also ping @Furzel does our backend currently support this well?

**Comment by ziggamon** [comment]
@Furzel What's latest status on this? This is the fix that went into master?

**Comment by Furzel** [comment]
I did the updates but on the "legacy" widget since I had no idea we stopped using it, need to port that to the currently used branch.

Here is the commit : https://github.com/bitrefill/airfill-widget/commit/8558bce6041d2ad824d796cd9c05e8e25f011f02

**Comment by williamsandstrom** [comment]
https://github.com/bitrefill/airfill-widget/commit/adddec4ed115c1f25c4c77c36337e24a536855a2
