### ISSUE TITLE
Widget translation

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#20]
Bringing this up here for discussion. What do we do for translating both the widget and accounts? Ping @mrlundis you were supposed to do digging into the subject on behalf of another project, has that digging happened yet?

**Comment by alfredringstad** [comment]
We did a lot of research for another project we work with. Our suggested solution is using a framework called [format-message](https://github.com/format-message/format-message) that provides possibility to do runtime translations with very little performance overhead. With this we could provide a default set of translation strings (in english) and allow the widget user to provide an object containing the translation strings as a config option.

There are also tools for "compiling" this so we get no runtime at all (but we need to build a bundle for every translation).

**Comment by ziggamon** [comment]
Interesting. 
Threw a quick glance at it now, what I like about it is that it seems to be able to run on the backend as well, so we could translate emails and such through the same tool. 

Are the language files reasonably standardized to be used with regular translation tools?

**Comment by mrlundis** [comment]
Yeah, there are however not that many online tools that has specific support for the syntax - but they are still usable. 

We might build a tool that provides a better translator experience (with auto complete and syntax highlighting, etc) within the scope of this other project that we could reuse here.

**Comment by ziggamon** [comment]
Is there a reason this lib doesn't use the standard syntaxes for translation? I remember .po-files from way back, and I've also seen JSON formats doing similar. 

Would we need to throw out all of our existing translation work on localize.js or do you thinks there would be ways to import it? We don't use so much fancy grammar, no gender stuff etc :)

**Comment by mrlundis** [comment]
It's a JSON serialisable standard :) What is lacking is support for all the fancy plurals and gender stuff in most of the available online translation management tools. 

See https://formatjs.io/ and http://userguide.icu-project.org/formatparse/messages.

**Comment by ziggamon** [comment]
Interesting :) 

What's the relationship between formatjs.io and format-message ?

**Comment by ziggamon** [comment]
Also: In your research did you find good practices for how to determine / switch locales for users? I.e. what the localize.js bar currently does for us.

**Comment by mrlundis** [comment]
- formatjs.io is a Yahoo-project from the start, but they have received a wide community adoption in the last few years. 
- The format-message project provide an alternate, more flexible implementation following the same standards.
- Both projects use the new Intl APIs that's available in all modern browsers (and easily polyfilled otherwise)

There is a package for auto-detecting the language based on the users browser settings available through the format-message project. This is usually sufficient.

**Comment by ziggamon** [comment]
Interesting. Sounds like a good strategy all this!

Have you already started implementing this in the other project?

Did you also find the best place to host the translation files themselves and/or to order translations?

**Comment by mrlundis** [comment]
Yeah, we have started to use this in the other project. The question of delivery is still very much unsolved though. 

We could easily host this ourselves to get started, but using a platform that automates this for us would be preferable. Deciding on such a platform is in our roadmap for the other project.

**Comment by ziggamon** [comment]
"The question of delivery"? 

Keep us posted re your findings on translation platforms. Probably it makes sense using something like transifex (or whatever the kids are using these days instead of that) to host and have translators have an easy interface to log in and do translations.

**Comment by mrlundis** [comment]
Delivery as in:
- Have translations in repo and serve them ourselves, or
- Have translations somewhere else and still serve them ourselves, or
- Use a 3rd party tool that updates the translations in our repo or wherever we store them
- Use a 3rd party tool that does dynamic delivery/loads translations on demand
