### ISSUE TITLE
User did not see "show all providers"

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#22]
First user feedback :)

User didn't see Tigo Ghana, because it was behind the "show all".

Proposing that we a) make the "show all" button look more distinct from a regular operator
b) Don't shrink that way if <=6 operators in a country.

**Comment by wille** [comment]
@ziggamon Is this still an issue? Can't reproduce

**Comment by ziggamon** [comment]
Yes. The behavior has not been changed. 

<img width="811" alt="screen shot 2018-02-15 at 16 51 26" src="https://user-images.githubusercontent.com/92292/36250475-86bccf76-1270-11e8-9f08-529faf395cf5.png">

**Comment by ziggamon** [comment]
(One of the items in the row is not like the others :)
