### ISSUE TITLE
Better handling of non-identified operators

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#23]
Try to search for number +1 876-817-6338. (this is currently a jamaica bug but the same applies whenever a number does not lead to an operator being identified)

Some issues: 
User gets led to a screen to chose operator, but that screen has no instructions about what's going on.

Triggers big red "There was an unexpected error. You might need to reload the current page."

No way to change the phone number (in case it was entered incorrectly)

Back button leaves the refill flow entirely

**Comment by wille** [comment]
![image](https://user-images.githubusercontent.com/18327818/36252985-9a2f5f8a-1246-11e8-9185-ed064206ba8a.png)

Does this look like it's supposed to?
