### ISSUE TITLE
migrate react-toolbox to material-ui

### ISSUE THREAD

**Issue by wille** [bitrefill/airfill-widget#27]
already done in the dashboard, I'll do the same for the widget on the widget2.0-comboinput branch

**Comment by williamsandstrom** [comment]
49f8db1

**Comment by williamsandstrom** [comment]
found a few buttons that lost their colors after migration to mui
- confirm payment button color
- the `continue` button gets wider and doesn't gray out when clicked after selected amount

**Comment by williamsandstrom** [comment]
material ui related stuff is discussed here https://github.com/bitrefill/bitrefill-dashboard/pull/182
