### ISSUE TITLE
Pre-loaded number makes widget unusable

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#37]
![logo](https://d2ffutrenqvap3.cloudfront.net/items/0W0H1g3q0z1a3S3u1K3f/Screen%20Recording%202018-02-19%20at%2002.57%20PM.gif?v=05062fad "")

**Comment by wille** [comment]
I'm unable to recreate this issue. @littlemooon could you check if you can recreate this? I've tried in fresh states locally, on account.bitrefill.com and in the `new-design` branch.

![gif](https://user-images.githubusercontent.com/18327818/36415780-67f87d8c-1627-11e8-9835-53b61fc9d82e.gif)

**Comment by ziggamon** [comment]
The issue seems to mainly happen when the number is preloaded, i.e. cached or otherwise "already there" when the widget loads.
