### ISSUE TITLE
Widget UI improvements

### ISSUE THREAD

**Issue by wille** [bitrefill/airfill-widget#38]
There is still some polishing needed on the widget after the 3.0 release.

- [x] `Order` > `Order ID`
- [ ] Order ID label should be more prominent
- [x] Easy selecting/copying of following fields (copy on click? How will we notify the user?)
  - [x] Bitcoin address
  - [x] Amount in BTC/altcoin
  - [x] Order ID
- [ ] Phone number should be more prominent
- [ ] The price in (USD) should be less prominent
- [x] `Open Wallet` > `Open in Wallet`
- [x] Expired orders `New order` button should restart the order instead of resetting the whole state.
- [x] Increase the width of the payment menu a bit as it doesn't look as good after we changed the payment method descriptions
- [x] Remove order expiration countdown on confirmed page etc
- [x] QR code static size on mobile devices

Expand this list as more things are found

**Comment by wille** [comment]
@mrlundis @ziggamon

**Comment by wille** [comment]
Clicking amount, payment address, order ID etc will now copy to clipboard and display the following tooltip

![image](https://user-images.githubusercontent.com/18327818/36899391-351213c4-1e1f-11e8-8a64-cdee23d68e07.png)

**Comment by wille** [comment]
I'll merge my current UI changes and wait for instructions on how stuff should be styled.

**Comment by ziggamon** [comment]
Go ahead. But maybe share some screenshots first?

**Comment by wille** [comment]
Closing this as lots of UI related stuff is happening.
