### ISSUE TITLE
Payment method switching and order creation

### ISSUE THREAD

**Issue by wille** [bitrefill/airfill-widget#40]
In order for us to get coin payment addresses from the backend we create a new order each time we switch payment method.

If switching from bitcoin to account balance, order generation is not needed. If fixed, we can save some time the user has to wait when the widget requests the order (at max like 1 sec but still)

- [x] Keep track of existing orders so we don't create more than one for each coin
- [x] Don't default to Bitcoin order

**Comment by Furzel** [comment]
The widget could keep track of the order it creates for each currency and switch between them if they already exist. 

This way we create a maximum of 1 order / currency
