### ISSUE TITLE
Better info in "Waiting for confirmation" view

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#44]
After a user makes a bitcoin payment they are super insecure about everyhing in the world. 

We have some info on the equivalent screen on www.bitrefill.com, including a link to transactioncheck.bitrefill.com and some other text. Would be good if the equivalent was in the same screen in the widget.

**Comment by wille** [comment]
![image](https://user-images.githubusercontent.com/18327818/37098868-46d7f9a8-221f-11e8-830a-e178aaf87a17.png)

**Comment by ziggamon** [comment]
Timer should not be visible after payment is received

**Comment by wille** [comment]
@ziggamon it's because I'm forcing the payment detected page to be shown, so it's only in dev.
