### ISSUE TITLE
Operator timeout

### ISSUE THREAD

**Issue by wille** [bitrefill/airfill-widget#49]
If an operator times out, and the backend returns  `503`, show a better error than this

![image](https://user-images.githubusercontent.com/18327818/37466558-56b225fc-285e-11e8-9378-14b76ce28d52.png)

**Comment by ziggamon** [comment]
I'd even generalize that to make sure to catch any unexpected error and give a standard reply.

Maybe even introduce some error codes (that user could paste into a support ticket) that would help us search for the issue in source code and logs

**Comment by wille** [comment]
Added text that says `An unknown error occured`.
