### ISSUE TITLE
Better display of partial payments

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#57]
Copy UX from current bitrefill-web

**Comment by Furzel** [comment]
Handled through slack ;)

**Comment by wille** [comment]
I'll just drop this here for reference

![image](https://user-images.githubusercontent.com/18327818/38610577-94369ef2-3d81-11e8-8b8f-b1f198bf072b.png)

**Comment by ziggamon** [comment]
So there is a bug in the www partial payment code? Is it backend-side? Please provide more info if you have any

**Comment by wille** [comment]
![image](https://user-images.githubusercontent.com/18327818/38617239-bc70450c-3d96-11e8-829d-db11e5cb2a6d.png)

https://github.com/bitrefill/airfill-widget/pull/59

**Comment by Maximization** [comment]
@wille Is the NaN thing localhost related or is it a bug?
