### ISSUE TITLE
Widget didn't display PIN code

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#64]
Tested a buy of Spotify voucher, refill was successful but no voucher PIN was displayed in my account widget. 

Unfortunately I didn't manage to screenshot the problem

Here is the order
https://bitrefill-support.herokuapp.com/order/5ace4a2d3d593e0004beb1b6

**Comment by wille** [comment]
I'll look into this ASAP.

**Comment by wille** [comment]
@ziggamon 
![image](https://user-images.githubusercontent.com/18327818/38725194-db38727c-3f06-11e8-8389-8a6371ea60dc.png)

I'm also thinking we change the `Buy another refill` etc to something like `Buy another PIN` or `Buy another voucher`.

**Comment by ziggamon** [comment]
The timer is still ticking.

"The refill delivery has been confirmed by the operator" is probably also the wrong wording for a voucher, better would be "See below for instructions on applying your voucher code". 

Other than that things are looking ok. 

I've generally been thinking that it may be time to look over our wordings for issues like this. Maybe we should open a separate ticket for that tho. 

We still need the delivery page to look different from the order page so that the user notices that something happened but that's also a separate ticket.

**Comment by wille** [comment]
The timer is only ticking if payment status is not set (new order) or when the status is `partial`. I force display the delivered view when debugging so that's why it is shown in the screenshot.

I'll fix the header wording and roll this out asap.

**Comment by ziggamon** [comment]
If you force status to be "delivered" then the ticker reasonably shouldn't be there?
And most importantly it should start ticking behind the scenes (separate ticket).

**Comment by wille** [comment]
https://github.com/bitrefill/airfill-widget/blob/master/src/components/Order/Payment.js#L43

Adding `return RefillDelivered;` to the top of that function. `paymentStatus.status` will still be whatever.

[Here](https://github.com/bitrefill/airfill-widget/blob/master/src/components/Order/PaymentLayout.js#L167) is the logic for deciding to show ticker or not

**Comment by wille** [comment]
![screenshot_2018-04-16_08-55-27](https://user-images.githubusercontent.com/18327818/38794188-83708264-4154-11e8-8925-eb9a402d1c5d.png)

**Comment by ziggamon** [comment]
Good stuff!

Re your question about the button: Maybe we can change it to "Make another order" ? 

And if the refill failed we could rename it "retry order"? 

I'll bring it up during the call today, we have a couple of places where we're starting to have issues with wording, could be good to settle on a policy.
