### ISSUE TITLE
[Maybe?] Widget expired message from a past order can overwrite current order

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#65]
Not critical, but I'm pretty sure I didn't manage to screenshot the bug in #64 was because the widget went into "expired" state about another order. Please check if this is something that is possible and add a check so that one order can't expire another order.

Also make sure that a successful order can't be expired :)

**Comment by wille** [comment]
Lowered the expiration time to 1 minute to test and created an order, then created a new one in the same session. The first order that had 30 seconds left when I created the second didn't trigger any expired state.
