### ISSUE TITLE
First load: If no country found, show the "international" products

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#70]
Alternatively maybe we should support all countries in the widget, and if the country isn't supported for top ups we only show the international stuff?

**Comment by wille** [comment]
I'd say we allow all countries and just attach international orders to them. This will require some backend work. @Furzel

**Comment by ziggamon** [comment]
Doesn't really need backend work? Just don't filter out any countries in the flag widget and if the pricelist is missing that particular country then show an error and display the international products?

**Comment by wille** [comment]
The widget does not know what countries that exists. I think it's a better solution to have the backend generate this than to hard code it, and it will not require any changes to the widget.

**Comment by Furzel** [comment]
If we do it in the backend where do we want it to be a thing ? Widget ? Website ? User pricelist ? API ? it impacts everything when you touche the pricelist. If it's simpler we could add a call to get international operators so the frontend can call that if it hits a country not on the pricelist.

**Comment by wille** [comment]
ref https://github.com/bitrefill/airfill-widget/commit/1f6d26df74a9f46d64ed3f0be55c57066c9e2eba

**Comment by wille** [comment]
need to fix tests failing related to this and cherry-pick changes to master, then it'll be published.
