### ISSUE TITLE
International country appears twice

### ISSUE THREAD

**Issue by Maximization** [bitrefill/airfill-widget#71]
![Bitrefill.jpg](https://images.zenhubusercontent.com/59d3acfbb0222d5de47a1acd/c46176a5-2703-4e87-8ff3-162dc4fba98c)

**Comment by wille** [comment]
![image](https://user-images.githubusercontent.com/18327818/38979550-c06d94fa-43ba-11e8-9d6a-6bff8ae6211a.png)

Backend related, gets two different international countries.

Maybe remove international completely and instead when https://github.com/bitrefill/airfill-widget/issues/70 is done we'll just let empty countries contain international products

**Comment by Furzel** [comment]
This is still happening ? Damn, I thought I fixed it. One of our provider is sending us the XA part for some operator that we disabled. Somehow it managed to register the 'country' anyway

**Comment by Maximization** [comment]
Issue moved to [bitrefill/bitrefill-backend #415](https://github.com/bitrefill/bitrefill-backend/issues/415) via [**ZenHub**](https://www.zenhub.com/)
