### ISSUE TITLE
Steps for payment method selector and number input

### ISSUE THREAD

**Issue by wille** [bitrefill/airfill-widget#79]
Payment method and number should have their own sections/steps in the widget

**Comment by wille** [comment]
I'm setting this as blocked since I need finished design for the new number/account input step, payment method picker step and the finalize order step. Until then, I'll prepare what I can like icons

**Comment by ziggamon** [comment]
How does it look now, can you push a demo somewhere?

I think the exact same fields as before but with new steps would already be a step forward

**Comment by wille** [comment]
Select amount (button styling is off)
![image](https://user-images.githubusercontent.com/18327818/39755725-3dc78e86-52c7-11e8-9625-dd659e262b03.png)

Select phone number (took number input from amount view, looks bad, needs some design here)
![image](https://user-images.githubusercontent.com/18327818/39755729-47485742-52c7-11e8-9eb7-375fb0e396d8.png)

Select payment method. I would like to add icons for all payment methods (like the new design in figma)
![image](https://user-images.githubusercontent.com/18327818/39755747-54d29b0c-52c7-11e8-8581-54e0d209401a.png)

and finally the final step. Payment method picker here will be removed.
![image](https://user-images.githubusercontent.com/18327818/39755762-60cf90c2-52c7-11e8-96ae-9e4179f412fb.png)

**Comment by ziggamon** [comment]
I think you can push it out already, it's a strict improvement vs what we've had this far.

Can you make the phone input use the big phone input that we use when we collect number first? Or is there something blocking that?

**Comment by wille** [comment]
This is not complete and would be a mess if we were to release it now, I need to remove the payment menu in the last step (and just keep the label) and fix some styling. Another thing I'd like to do is to use these icons instead of the text icons. What do you say?

![image](https://user-images.githubusercontent.com/18327818/39756316-62893aba-52c9-11e8-8dda-b2f0be0217ce.png)

**Comment by ziggamon** [comment]
>I need to remove the payment menu in the last step (and just keep the label)

Can you explain?

> I'd like to do is to use these icons 

Agree. Maybe Anna can give you the files she used?

**Comment by wille** [comment]
@ziggamon 

The payment method switcher we currently should be removed now when we have a separate step for picking payment method. If the user wants to change payment method during order creation, he or she should go back to that step. This will actually improve stuff alot since we do not longer need any hot order creation under the hood on the last step.

**Comment by wille** [comment]
done. what's missing is different gray shades for each collapsed header (change payment, change provider) but that isn't too urgent and will need some rewriting.
