### ISSUE TITLE
Standalone build produces 2 output bundles

### ISSUE THREAD

**Issue by wille** [bitrefill/airfill-widget#81]
Run `webpack --config config/standalone.js` (`yarn build:standalone`)

```
Hash: a075fd9ec5991b2d4c97
Version: webpack 4.6.0
Time: 8720ms
Built at: 2018-05-08 12:15:42
                             Asset      Size  Chunks                    Chunk Names
    vendors~react-pusher.bundle.js  65.6 KiB       0  [emitted]         vendors~react-pusher
                         widget.js   877 KiB       1  [emitted]  [big]  main
vendors~react-pusher.bundle.js.map   141 KiB       0  [emitted]         vendors~react-pusher
                     widget.js.map  2.78 MiB       1  [emitted]         main
```

I believe this is the cause

https://github.com/bitrefill/airfill-widget/blob/master/src/components/Pusher.js#L5
https://github.com/bitrefill/airfill-widget/blob/master/src/payment-methods.js#L25

Standalone bundle should always be one single bundle so it can easily be embedded with a `<script/>`.

**Comment by littlemooon** [comment]
@wille all done

the webpack limit chunk count plugin allows us to do this in one sweep without changing any async code 👌 

https://github.com/bitrefill/airfill-widget/pull/82

**Comment by wille** [comment]
awesome
