### ISSUE TITLE
Skip payment method selecting if only one available

### ISSUE THREAD

**Issue by wille** [bitrefill/airfill-widget#84]
In dashboard we only have account balance as payment method and the picker step is unnecessary.

**Comment by wille** [comment]
I'll postpone this until we get started with the widget redesign

**Comment by ziggamon** [comment]
Yeah, no need, but still makes sense to skip this if there is a balance on the account that can afford to pay for the order (in the B2C accounts case)

**Comment by wille** [comment]
https://github.com/bitrefill/airfill-widget/issues/108
