### ISSUE TITLE
Unregistered user email

### ISSUE THREAD

**Issue by wille** [bitrefill/airfill-widget#94]
Email input field for unregistered users are broken. Orders gets created with empty email.

**Comment by littlemooon** [comment]
@wille are you sure about this?? i can see it in prod

![image](https://user-images.githubusercontent.com/2467416/40435497-ab49caea-5ea8-11e8-931d-c77c8ddfc139.png)

**Comment by littlemooon** [comment]
definitely there for me in prod...

maybe you had an old version. it was only added last night: https://github.com/bitrefill/bitrefill-dashboard/commit/70c8616e9c7cd9169fb633fce3f26a2701dcc149

![image](https://user-images.githubusercontent.com/2467416/40436152-453414a2-5eaa-11e8-9969-10bbc3b45f68.png)

**Comment by wille** [comment]
Great!
