### ISSUE TITLE
Malformed phone number triggers weird error

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#99]
![](https://dzwonsemrish7.cloudfront.net/items/0Y202B0O3o2z0F373H1D/Screen%20Recording%202018-06-07%20at%2011.22%20AM.gif?v=6f4b2fac)
Several bugs in this one:

- UI should have indicated that the number is incorrect
- Caret jumping (#98) increases likelihood of this bug
- Phone number is sent to api without international code (because malformed)
- Error handling is missing, exposes JS errors

**Comment by wille** [comment]
Error handling fixed in https://github.com/bitrefill/airfill-widget/pull/100
